---

- name: Check if PWA is already installed
  stat:
    path: "{{ pwa_demo_scripts_dir }}"
  register: scriptdirexists

- name: Create PWA Demo script directory
  file:
    path: "{{ pwa_demo_scripts_dir }}"
    state: directory
    owner: "{{ pwa_demo_user }}"
    group: "{{ pwa_demo_group }}"
    mode: 0750
  when: not scriptdirexists.stat.exists

- name: Copy PWA Demo install/uninstall scripts
  copy:
    src: "{{ item }}"
    dest: "{{ pwa_demo_scripts_dir }}/{{ item }}"
    owner: "{{ pwa_demo_user }}"
    group: "{{ pwa_demo_group }}"
    mode: 0750
  with_items:
    - install-pwa.sh
    - uninstall-pwa.sh
  when: not scriptdirexists.stat.exists

- name: Copy PWA Demo default config
  copy:
    src: "{{ item }}"
    dest: "{{ pwa_demo_scripts_dir }}/{{ item }}"
    owner: "{{ pwa_demo_user }}"
    group: "{{ pwa_demo_group }}"
    mode: 0640
  with_items:
    - config_default.json
  when: not scriptdirexists.stat.exists

- name: Create PWA Demo site config file
  template:
    src: config_site.json.j2
    dest: "{{ pwa_demo_scripts_dir }}/config_{{ pwa_demo_config_name }}.json"
    owner: "{{ pwa_demo_user }}"
    group: "{{ pwa_demo_group }}"
    mode: 0640
  when: not scriptdirexists.stat.exists

- name: Run PWA Demo installation
  become: yes
  become_user: "{{ pwa_demo_user }}"
  ansible.builtin.shell: ./install-pwa.sh config_site.json
  args:
    chdir: "{{ pwa_demo_scripts_dir }}"
  when: not scriptdirexists.stat.exists
  register: out

- name: PWA Demo installation output
  debug: var=out.stdout_lines

  # Symlink /var/www/data-pwa/current to /var/www/data-pwa/venia-concept
- name: Check that the current path exists
  stat:
    path: "{{ pwa_demo_env_root }}/current"
  register: current_path

- name: Link venia-concept directory to current
  file:
    src: "{{ pwa_demo_magento_root }}"
    dest: "{{ pwa_demo_env_root }}/current"
    owner: "{{ pwa_demo_user }}"
    group: "{{ pwa_demo_group }}"
    state: link
    force: yes
  when: 
    - not current_path.stat.exists 
    - not scriptdirexists.stat.exists
