---
- name: adding user "{{ pwa_demo_user }}" to group "{{ magento_demo_group }}"
  user:
    name: "{{ pwa_demo_userr }}"
    groups: "{{ magento_demo_group }}"
    append: yes
  when: not pwa_demo_type_upward_js

- name: Install yarn package globally
  community.general.npm:
    name: yarn
    global: yes

- name: Create PWA Demo script directory
  file:
    path: "{{ pwa_demo_scripts_dir }}"
    state: directory
    owner: "{{ pwa_demo_user }}"
    group: "{{ pwa_demo_group }}"
    mode: 0750

- name: Copy PWA Demo install/uninstall scripts
  copy:
    src: "{{ item }}"
    dest: "{{ pwa_demo_scripts_dir }}/{{ item }}"
    owner: "{{ pwa_demo_user }}"
    group: "{{ pwa_demo_group }}"
    mode: 0750
  with_items:
    - install-pwa.sh
    - uninstall-pwa.sh

- name: Copy PWA Demo default config
  copy:
    src: "{{ item }}"
    dest: "{{ pwa_demo_scripts_dir }}/{{ item }}"
    owner: "{{ pwa_demo_user }}"
    group: "{{ pwa_demo_group }}"
    mode: 0640
  with_items:
    - config_default.json

- name: Create PWA Demo site config file
  template:
    src: config_site.json.j2
    dest: "{{ pwa_demo_scripts_dir }}/config_{{ pwa_demo_config_name }}.json"
    owner: "{{ pwa_demo_user }}"
    group: "{{ pwa_demo_group }}"
    mode: 0640

- name: Copy custom script for Magento_UpwardConnector (upward-php)
  template:
    src: custom_script_site.sh.j2
    dest: "{{ magento_demo_scripts_dir }}/custom_script_site.sh"
    owner: "{{ magento_demo_user }}"
    group: "{{ magento_demo_group }}"
    mode: 0750
  when: not pwa_demo_type_upward_js
