---

- name: Check if PWA is already installed
  stat:
    path: "{{ pwa_demo_scripts_dir }}"
  register: scriptdir

- name: PWA install script doesn't not exists
  include_tasks: install.yml
  when: not scriptdir.stat.exists
